config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :categories
  resources :answers
  resources :users, only: :show
  resources :donations, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :scores
  has_many :answers
  has_many :orders
  mount_uploader :photo, PhotoUploader

  def value_create(date)
    answers.where(date: date).map { |a| a.option.weight }.sum
  end

  def travel_value_create(date)
    answers.where(date: date).where(category_id: 1).map { |a| a.option.weight }.sum
  end

  def home_value_create(date)
    answers.where(date: date).where(category_id: 2).map { |a| a.option.weight }.sum
  end

  def show_score
    scores.map(&:value).last
    #if scores.map(&:value).sum
    #   scores.map(&:value).sum
    #else
    #  answers.map { |a| a.option.weight }.sum
    # end
    # current_user.scores.map {|s| s.value}.sum
  end

  def show_travel_category_score
    # answers.where(category_id: category_id).map(&:option).map(&:weight).sum
    scores.map(&:travel_value).last
  end

  def show_home_category_score
    # answers.where(category_id: category_id).map(&:option).map(&:weight).sum
    scores.map(&:home_value).last
  end

  def show_consumption_category_score
    # answers.where(category_id: category_id).map(&:option).map(&:weight).sum
    scores.map(&:consumption_value).last
  end

  def show_score_breakdown
    scores.map(&:value)
  end

  def score_object
    score = scores.last
    remainder = 100 - (score.travel_value + score.home_value + score.consumption_value + score.society_value)
    @score_total = { travel: score.travel_value, home: score.home_value, consumption: score.consumption_value, society: score.society_value, remainder: remainder }
  end

  def score_history_object
    @score_historicals = scores.map { |score|
      {
        y: score.value,
        x: score.date
      }
    }
  end

  def score_travel_history_object
    @score_travel_historicals = scores.map { |score|
      {
        y: score.travel_value,
        x: score.date
      }
    }
  end

  def score_home_history_object
    @score_home_historicals = scores.map { |score|
      {
        y: score.home_value,
        x: score.date
      }
    }
  end

  def score_consumption_history_object
    @score_consumption_historicals = scores.map { |score|
      {
        y: score.consumption_value,
        x: score.date
      }
    }
  end

  def score_society_history_object
    @score_society_historicals = scores.map { |score|
      {
        y: score.society_value,
        x: score.date
      }
    }
  end

  def show_travel_category_score_breakdown
    # answers.where(category_id: category_id).map(&:option).map(&:weight)
    scores.map(&:travel_value)
  end

  def show_home_category_score_breakdown
    # answers.where(category_id: category_id).map(&:option).map(&:weight)
    scores.map(&:home_value)
  end

  def show_consumption_category_score_breakdown
    # answers.where(category_id: category_id).map(&:option).map(&:weight)
    scores.map(&:consumption_value)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  after_action :add_score_to_user, only: :create

  private

  def add_score_to_user
    resource.scores.create!(category_id: 1, date: Date.today, value: 0, travel_value: 0, home_value: 0, consumption_value: 0, society_value: 0)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @photo = @user.photo
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  # def show

  # end

end

app/views/users/_user.html.erb
<!-- <div>
  <p>Your Overall Score</p>
  <p><%=  @user.show_score %></p>
</div>
<div>
  <p>Your travel Score</p>
  <p id="travel_value"><%=  @user.show_travel_category_score%></p>
</div>
<div>
  <p>Your home Score</p>
  <p id="home_value"><%=  @user.show_home_category_score%></p>
</div>
<div>
  <p>Your consumption Score</p>
  <p id="consumption_value"><%=  @user.show_consumption_category_score%></p>
</div>
<div>
  <p>Your overall Score history</p>
  <p id="score_history_value"><%=  @user.show_score_breakdown%></p>
</div>
<div>
  <p>Your travel Score history</p>
  <p><%=  @user.show_travel_category_score_breakdown%></p>
</div>
<div>
  <p>Your home Score history</p>
  <p><%=  @user.show_home_category_score_breakdown%></p>
</div> -->
<!-- <div>
  <p>Your consumption Score history</p>
  <p id="consumption_value"><%=  @user.show_consumption_category_score_breakdown%></p>
</div>
<p>Dates of the scores</p>
<ul id="dates">
  <% @user.scores.each do |score| %>
      <li><%= score.date %></li>
  <% end %>
</ul> -->
<% min_date = @user.scores.map(&:date).sort.first %>
<% max_date = @user.scores.map(&:date).sort.last %>
<div class="anotherscore fade-in one">
  <p class="plus">
  <%= link_to "+", new_answer_path,  class: "plussign"  %>
  </p>
  <p id="displaytypewriter"></p>
</div>
 <div class="payment fade-in one">
  <div class="pound">
  <%= link_to donations_path,  class: "poundsign" do %>
  <%= image_tag("heart.svg", width: 35, height: 35, class: "heart") %>
<!--       <p>£ </p>
 --> <!--      <p id="donate">Donate</p> -->
  <% end %>
  </div>
  <p id="displaytypewriter2"></p>
</div>

<div class="chart-container">
  <div class="scoreChart fade-in two" data-score_total="<%= @user.score_object.to_json %>">
  <canvas id="myChart" width="400" height="400"></canvas>
         <div class="button-show">
  <a href="#" class="historyButton btn-standard-black">Historical Overall Scores</a>
</div>
  <div class="absolute-center text-center">
      <p><%= @user.show_score %></p>
      <p id="denominator">100</p>
    </div>
  </div>

<!--    <div class="social">
        <p class="socialclick fade-in two">Share your score</p>
        <div class="social-icons hide">
        <%= link_to 'https://www.facebook.com/', target: :_blank, class:"icon-link" do %>
       <i class="fab fa-facebook icon"></i>
     <% end %>
     <%= link_to 'https://www.linkedin.com/', target: :_blank, class:"icon-link" do %>
       <i class="fab fa-linkedin icon"></i>
     <% end %>
      </div>
    </div> -->
</div>

<div class="scoreHistoryChart hide fade-in one" data-score-historicals="<%= @user.score_history_object.to_json %>" data-min-date="<%= min_date %>" data-max-date="<%= max_date %>">
  <div class="button-show">
  <a href="#" class="button btn-standard-black">Overall Score</a>
</div>
<canvas id="myScoreHistoryChart" width="400" height="400"></canvas>
</div>
<div class="homeHistoryChart fade-in one" data-home_score_historicals=" <%= @user.score_home_history_object.to_json %>" data-min-date="<%= min_date %>" data-max-date="<%= max_date %>">
   <div class="button-show">
  <a href="#" class="button btn-standard-black">Overall Score</a>
</div>
<canvas id="myHomeHistoryChart" width="400" height="400"></canvas>
</div>

<div class="travelHistoryChart fade-in one" data-travel_score_historicals=" <%= @user.score_travel_history_object.to_json %>" data-min-date="<%= min_date %>" data-max-date="<%= max_date %>">
   <div class="button-show">
  <button class="button btn-standard-black">Overall Score</button>
</div>
<canvas id="myTravelHistoryChart" width="400" height="400"></canvas>
</div>

<div class="consumptionHistoryChart fade-in one" data-consumption_score_historicals=" <%= @user.score_consumption_history_object.to_json %>" data-min-date="<%= min_date %>" data-max-date="<%= max_date %>">
   <div class="button-show">
  <button class="button btn-standard-black">Overall Score</button>
</div>
<canvas id="myConsumptionHistoryChart" width="400" height="400"></canvas>
</div>

<div class="societyHistoryChart fade-in one" data-society_score_historicals=" <%= @user.score_society_history_object.to_json %>" data-min-date="<%= min_date %>" data-max-date="<%= max_date %>">
   <div class="button-show">
  <button class="button btn-standard-black">Overall Score</button>
</div>
<canvas id="mySocietyHistoryChart" width="400" height="400"></canvas>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="dashboard-body-content">
    <div class="dashboard-flex">

      <div class="dashboard-score-section">
<!--         <div class="dashboard-title fade-in one"><h1>your terrascore</h1>
</div> -->
        <hr />

        <%= render "user", user: @user %>

<!--         <div class="dashboard-link-section">
          <div class="dashboard-link-card">
            <h2>Add/Update a score</h2>
            <p>Choose a category:</p>
            <div class="dashboard-questionnaire-links">
              <%= link_to "Answer questions", new_answer_path,  class: "btn-standard-white"  %>
              <%= link_to "Travel", new_answer_path(category: "Travel"), class: "btn-standard-white" %>
              <br>
              <%= link_to "Home", new_answer_path(category: "Home"), class: "btn-standard-white" %>
              <br>
              <%= link_to "Charity", new_answer_path(category: "Charity"), class: "btn-standard-white" %>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>