config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :categories
  resources :answers
  resources :users, only: :show
  resources :donations, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :option
  belongs_to :category
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_questions

  # def index
  # end

  # def show
  # end

  def new           # GET /answers/new
    @answer = Answer.new
  end

  def create        # POST /answers
    option_ids = params[:options].split(",")
    travel_score = 0
    home_score = 0
    consumption_score = 0
    total_score = 0
    society_score = 0
    option_ids.each do |option_id|
      option = Option.find(option_id)
      Answer.create(user: current_user, option: option, date: DateTime.now, category: option.question.category)
      if option.question.category.name == "Travel"
        travel_score += option.weight
      elsif option.question.category.name == "Home"
        home_score += option.weight
      elsif option.question.category.name == "Consumption"
        consumption_score += option.weight
      else
        society_score += option.weight
      end
      total_score += option.weight
    end
    Score.create(user: current_user, value: total_score, travel_value: travel_score, home_value: home_score, consumption_value: consumption_score, society_value: society_score, date: Date.today, category: Category.last)
    redirect_to user_path(current_user)
  end

  def edit          # GET /questions/:id/edit
  end

  def update        # PATCH /questions/:id
  end

  def destroy       # DELETE /questions/:id
  end

  private

  def set_questions
    # @questions = Question.where(category: params[:category])
    # @questions = Question.select { |q| q.category.name == params[:category] }
    @questions = Question.all
  end

  def answer_params
    params.require(:answer).permit(:option_id, :user_id, :date)
  end
end

app/views/answers/new.html.erb
<div class="progress-header">
  <div class="progress-container">
    <div class="progress-bar" id="myBar"></div>
  </div>
</div>

<div class="answer-new-container">

  <div class="category-section">

    <div class="category-header">
      <h1>Travel</h1>
      <p>Please answer the following questions about your travel lifestyle</p>
    </div>

    <div class="category-questions">
      <% @questions.where(category_id: 1).each do |question| %>
        <div class="question" id="<%= @questions.index(question) %>">
          <h4><%= question.content %></h4>
          <% question.options.each do |option| %>
              <input type="checkbox" name="answer" id="option-<%= option.id %>" class="options" data-option="<%= option.id %>">
              <span> <%= option.content %></span>
              <br>
              <br>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="category-section">

    <div class="category-header">
      <h1>Home</h1>
      <p>Please answer the following questions about your home</p>
    </div>

    <div class="questions">
      <% @questions.where(category_id: 2).each do |question| %>
        <div class="question" id="<%= @questions.index(question) %>">
          <h4><%= question.content %></h4>
          <% question.options.each do |option| %>
              <input type="checkbox" name="answer" id="option-<%= option.id %>" class="options" data-option="<%= option.id %>">
              <span> <%= option.content %></span>
              <br>
              <br>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="category-section">

    <div class="category-header">
      <h1>Consumption</h1>
      <p>Please answer the following questions about your food consumption</p>
    </div>

    <div class="category-questions">
      <% @questions.where(category_id: 3).each do |question| %>
        <div class="question" id="<%= @questions.index(question) %>">
          <h4><%= question.content %></h4>
          <% question.options.each do |option| %>
              <input type="checkbox" name="answer" id="option-<%= option.id %>" class="options" data-option="<%= option.id %>">
              <span> <%= option.content %></span>
              <br>
              <br>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="category-section">

    <div class="category-header">
      <h1 class="testben">Society</h1>
      <p>Please answer the following questions about your relationship with society</p>
    </div>

    <div class="questions">
      <% @questions.where(category_id: 4).each do |question| %>
        <div class="question" id="<%= @questions.index(question) %>">
          <h4><%= question.content %></h4>
          <% question.options.each do |option| %>
              <input type="checkbox" name="answer" id="option-<%= option.id %>" class="options" data-option="<%= option.id %>">
              <span> <%= option.content %></span>
              <br>
              <br>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>


  <div class="actions">
<!--     <button class="btn-standard-white" id="previous">Previous</button> -->
    <a href="#" class="btn-standard-black" id="next">Next Category</a>
    <button class="btn-standard-black" id="submit" data-url="<%= user_url(current_user) %>">Submit</button>
    <%#= link_to "Submit", user_path(current_user), id:"submit", class: "btn-standard-black"  %>

  </div>
</div>
<!--
    previousButton.classList.remove("invisible");
    previousButton.classList.add("visible"); -->


<!-- start with the Travel Section -->
<!--  -->