config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'pages#home'

  resources :categories
  resources :answers
  resources :users, only: :show
  resources :donations, only: [:index, :show]

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  monetize :price_cents

  mount_uploader :photo, PhotoUploader
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @donations = Donation.all
  end

  def show
    @donation = Donation.find(params[:id])
  end
end

app/views/donations/index.html.erb
<div class="container">
  <div class="donations-intro">
    <h1>Partnering Charities</h1>
    <p>Increase your terrascore by donating to one of the following charities </p>
  </div>
  <div class="cards">
    <% @donations.each do |donation| %>
    <div class="card">
      <%= cl_image_tag donation.photo %>
      <div class="card-infos">
        <h5 class="card-title"><%= link_to donation.name, donation_path(donation)  %></h5>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/donations/show.html.erb
<div class="container">

  <div class="charity-info">

    <div class="charity-info-text">
      <h1><%= @donation.name %></h1>
      <p><%= @donation.description %></p>
    </div>
    <%= cl_image_tag(@donation.photo, width: '100%') %>
  </div>

  <div class="donation-amount">
    <p>Specify your desired donation amount:</p>
    <%= form_tag orders_path do %>

      <span>£</span> <%= text_field_tag 'price', "", class: 'black-box' %>
      <%= hidden_field_tag 'donation_id', @donation.id %>
      <%= submit_tag 'Donate', class: 'btn-standard-black' %>
    <% end %>
  </div>

</div>